"""NeuroScope AI — Loader Utility (auto-generated by Notebook 00A)

Usage at the top of every notebook:
    import sys
    sys.path.insert(0, r'C:\\Users\\tejan\\OneDrive\\Desktop\\drive\\NeuroScope_AI')
    from neuroscope_loader import cfg, DEVICE, BASE
"""
import os, yaml, torch

BASE = r'C:\Users\tejan\OneDrive\Desktop\drive\NeuroScope_AI'

with open(os.path.join(BASE, "configs", "master_config.yaml"), encoding="utf-8") as f:
    cfg = yaml.safe_load(f)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def save_checkpoint(model, optimizer, epoch, loss, path, scheduler=None, extra=None):
    """Save training checkpoint."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    state = {
        "epoch": epoch, "loss": loss,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
    }
    if scheduler:
        state["scheduler_state_dict"] = scheduler.state_dict()
    if extra:
        state.update(extra)
    torch.save(state, path)


def load_checkpoint(path, model, optimizer, scheduler=None):
    """Resume from checkpoint. Returns next epoch number."""
    if not os.path.exists(path):
        print("  No checkpoint found - starting from scratch")
        return 0
    ckpt = torch.load(path, map_location=DEVICE, weights_only=False)
    model.load_state_dict(ckpt["model_state_dict"])
    optimizer.load_state_dict(ckpt["optimizer_state_dict"])
    if scheduler and "scheduler_state_dict" in ckpt:
        scheduler.load_state_dict(ckpt["scheduler_state_dict"])
    print(f'  Resumed epoch {ckpt["epoch"]}, loss {ckpt["loss"]:.4f}')
    return ckpt["epoch"] + 1


gpu = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU"
print(f"NeuroScope AI | Device: {gpu} | Root: {BASE}")
